/**
 * Résultats — Signature 3D IA
 * Version: 3.0 — Multilingue FR/EN + secteurs depuis PostgreSQL
 */

'use client'

import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { TrendingUp, Users, MessageSquare, BarChart2 } from 'lucide-react'
import { useLanguage } from '@/context/LanguageContext'
import { sectorsApi, type SectorDto } from '@/lib/api'

const GOLD      = '#D4881E'
const GOLD_DARK = '#B8720F'
const DARK      = '#1A1400'

const content = {
  fr: {
    label:    'Résultats',
    title:    <>Des chiffres qui <em style={{ color: GOLD, fontStyle: 'italic' }}>parlent d&apos;eux-mêmes</em></>,
    subtitle: 'Nos premières expériences génèrent déjà des résultats concrets pour nos clients.',
    sectorLabel: 'Secteurs que nous servons',
    closing: 'Les premiers témoignages clients seront publiés dès le déploiement des expériences en production — nous construisons pour la durée.',
    metrics: [
      { icon: Users,         value: '+500', label: 'Visiteurs uniques',  sub: 'sur les démos actives',  description: 'Visiteurs engagés sur nos expériences live' },
      { icon: MessageSquare, value: '+120', label: 'Interactions IA',    sub: 'questions traitées',     description: 'Réponses précises générées par Luxedia' },
      { icon: TrendingUp,    value: '+35',  label: 'Leads qualifiés',    sub: 'transmis aux clients',   description: 'Prospects convertis et transmis automatiquement' },
      { icon: BarChart2,     value: '98%',  label: 'Satisfaction',       sub: "taux de réponse IA",    description: 'Taux de pertinence des réponses Luxedia' },
    ],
  },
  en: {
    label:    'Results',
    title:    <>Numbers that <em style={{ color: GOLD, fontStyle: 'italic' }}>speak for themselves</em></>,
    subtitle: 'Our first experiences are already generating concrete results for our clients.',
    sectorLabel: 'Sectors we serve',
    closing: 'First client testimonials will be published upon production deployment — we build for the long term.',
    metrics: [
      { icon: Users,         value: '+500', label: 'Unique visitors',    sub: 'on active demos',       description: 'Engaged visitors on our live experiences' },
      { icon: MessageSquare, value: '+120', label: 'AI interactions',    sub: 'questions handled',     description: 'Precise answers generated by Luxedia' },
      { icon: TrendingUp,    value: '+35',  label: 'Qualified leads',    sub: 'forwarded to clients',  description: 'Converted prospects forwarded automatically' },
      { icon: BarChart2,     value: '98%',  label: 'Satisfaction',       sub: 'AI response rate',      description: 'Relevance rate of Luxedia answers' },
    ],
  },
}

const containerVariants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.1 } },
}

const cardVariants = {
  hidden:   { opacity: 0, y: 24 },
  visible:  { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] } },
}

export default function PreuveSociale() {
  const { lang } = useLanguage()
  const c = content[lang]
  const [sectors, setSectors] = useState<SectorDto[]>([])

  useEffect(() => {
    sectorsApi.getAll()
      .then((data) => setSectors(data as SectorDto[]))
      .catch(console.error)
  }, [])

  return (
    <section id="resultats" style={{ backgroundColor: '#FAFAF8', padding: '104px 0 96px', position: 'relative', overflow: 'hidden' }}>
      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundImage: 'radial-gradient(circle at 90% 10%, rgba(212,136,30,0.05) 0%, transparent 50%), radial-gradient(circle at 10% 90%, rgba(212,136,30,0.04) 0%, transparent 50%)', pointerEvents: 'none' }} />

      <div className="container-main" style={{ position: 'relative', zIndex: 1 }}>

        {/* Header */}
        <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }} style={{ textAlign: 'center', marginBottom: '72px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '12px', marginBottom: '20px' }}>
            <div style={{ width: '32px', height: '1px', backgroundColor: GOLD }} />
            <span style={{ fontSize: '10px', fontWeight: 700, letterSpacing: '0.32em', textTransform: 'uppercase', color: GOLD }}>{c.label}</span>
            <div style={{ width: '32px', height: '1px', backgroundColor: GOLD }} />
          </div>
          <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(2.2rem, 4vw, 3.2rem)', fontWeight: 300, color: DARK, letterSpacing: '-0.02em', lineHeight: 1.1, marginBottom: '20px' }}>{c.title}</h2>
          <p style={{ maxWidth: '460px', margin: '0 auto', fontSize: '15px', lineHeight: 1.75, color: '#6B6458', fontWeight: 300 }}>{c.subtitle}</p>
        </motion.div>

        {/* Métriques */}
        <motion.div variants={containerVariants} initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-60px' }} style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '20px', marginBottom: '32px' }} className="metrics-grid-custom">
          {c.metrics.map((m) => (
            <motion.div key={m.label} variants={cardVariants} className="metric-card" style={{ borderRadius: '16px', border: '1.5px solid #E8E2D4', backgroundColor: '#FFFFFF', padding: '32px 24px', textAlign: 'center', transition: 'all 0.3s ease', position: 'relative', overflow: 'hidden' }}>
              <div style={{ position: 'absolute', top: 0, left: '50%', transform: 'translateX(-50%)', width: '40px', height: '2px', backgroundColor: GOLD, borderRadius: '0 0 4px 4px' }} />
              <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '20px' }}>
                <div style={{ width: '48px', height: '48px', borderRadius: '12px', backgroundColor: '#F5F0E8', border: '1px solid #E8E2D4', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <m.icon size={20} strokeWidth={1.5} style={{ color: GOLD_DARK }} />
                </div>
              </div>
              <div style={{ fontFamily: 'var(--font-display)', fontSize: '2.6rem', fontWeight: 300, color: DARK, lineHeight: 1, marginBottom: '10px', letterSpacing: '-0.02em' }}>{m.value}</div>
              <div style={{ fontSize: '13.5px', fontWeight: 600, color: DARK, marginBottom: '4px', letterSpacing: '-0.01em' }}>{m.label}</div>
              <div style={{ fontSize: '12px', color: '#8A7A5A', fontWeight: 400, marginBottom: '16px' }}>{m.sub}</div>
              <div style={{ fontSize: '11.5px', color: '#B0A090', lineHeight: 1.5, paddingTop: '14px', borderTop: '1px solid #F0EBE0' }}>{m.description}</div>
            </motion.div>
          ))}
        </motion.div>

        {/* Secteurs depuis PostgreSQL */}
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6, delay: 0.35 }} style={{ borderRadius: '20px', border: '1.5px solid #E8E2D4', backgroundColor: '#FFFFFF', padding: '48px 40px', textAlign: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '12px', marginBottom: '28px' }}>
            <div style={{ width: '24px', height: '1px', backgroundColor: '#E8E2D4' }} />
            <span style={{ fontSize: '10px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.3em', color: '#8A7A5A' }}>{c.sectorLabel}</span>
            <div style={{ width: '24px', height: '1px', backgroundColor: '#E8E2D4' }} />
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: '10px', marginBottom: '32px' }}>
            {sectors.map((sector) => (
              <span key={sector.id} className="sector-badge" style={{ borderRadius: '8px', border: '1.5px solid #E8E2D4', backgroundColor: '#FAFAF8', padding: '9px 22px', fontSize: '11px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.15em', color: '#5A4E3A', transition: 'all 0.25s ease', cursor: 'default' }}>
                {sector.name}
              </span>
            ))}
          </div>
          <p style={{ maxWidth: '500px', margin: '0 auto', fontSize: '13.5px', lineHeight: 1.75, color: '#8A7A5A', fontWeight: 300 }}>{c.closing}</p>
        </motion.div>
      </div>

      <style>{`
        .metric-card:hover { border-color: rgba(212,136,30,0.35) !important; transform: translateY(-4px); box-shadow: 0 16px 40px rgba(0,0,0,0.07) !important; }
        .sector-badge:hover { background-color: rgba(212,136,30,0.06) !important; border-color: rgba(212,136,30,0.35) !important; color: ${GOLD_DARK} !important; }
        @media (max-width: 900px) { .metrics-grid-custom { grid-template-columns: repeat(2, 1fr) !important; } }
        @media (max-width: 480px) { .metrics-grid-custom { grid-template-columns: 1fr !important; } }
      `}</style>
    </section>
  )
}
